services:
  docmost:
    image: docmost/docmost:latest
    environment:
      - APP_URL=https://${APP_HOST}
      - APP_SECRET=${APP_SECRET}
      - DATABASE_URL=postgres://${DB_USER}:${DB_PASSWORD}@${DB_HOST}:${DB_PORT}/${DB_NAME}
      - REDIS_URL=redis://${REDIS_HOST}:${REDIS_PORT}/${REDIS_DB}
      - PORT=5698
    volumes:
      - docmost_data:/app/data/storage
    expose:
      - 5698
    deploy:
      placement:
        constraints:
          - node.role == worker
volumes:
  docmost_data: {}
