version: '3'

services:
  actual-server:
    image: actualbudget/actual-server:latest
    container_name: actual-server
    volumes:
      - actual-data:/data
    restart: unless-stopped
    deploy:
      placement:
        constraints:
          - node.role == worker
    expose:
      - 5060
volumes:
  actual-data: