version: '3'

services:
  actual-server:
    image: actualbudget/actual-server:latest
    container_name: actual-server
    ports:
      - "5006:5006"
    volumes:
      - actual-data:/data
    restart: unless-stopped

volumes:
  actual-data: