services:
  cyberchef:
    image: gchq/cyberchef:latest
    deploy:
      placement:
        constraints:
          - node.role == worker
    environment:
      - NODE_OPTIONS=--max_old_space_size=2048
    expose:
      - 8080