services:
  ghost:
    image: ghost:alpine
    environment:
      - NODE_ENV=production
      - database__client=postgres
      - database__connection__host=${DB_HOST}
      - database__connection__user=${DB_USER}
      - database__connection__password=${DB_PASSWORD}
      - database__connection__database=${DB_NAME}
      - server__port=8632
      - url=https://${GHOST_HOST}
      - server__host=0.0.0.0
      - admin__url=https://${GHOST_ADMIN_HOST}
    expose:
      - 8632
    volumes:
      - ghost_data:/var/lib/ghost/content
volumes:
  ghost_data: {}
