services:
  ghost:
    image: ghost:alpine
    environment:
      - NODE_ENV=production
      - database__client=mysql
      - database__connection__host=${DB_HOST}
      - database__connection__user=${DB_USER}
      - database__connection__password=${DB_PASSWORD}
      - database__connection__database=${DB_NAME}
      - database__connection__port=${DB_PORT}
      - server__port=8632
      - url=https://${GHOST_HOST}/
      - server__host=0.0.0.0
      - mail__transport=SMTP
      - mail__options__host=${MAIL_HOST}
      - mail__options__port=${MAIL_PORT}
      - mail__from=${MAIL_FROM}
      - mail__options__secure=${MAIL_SECURE}
      - mail__options__auth__user=${MAIL_USER}
      - mail__options__auth__pass=${MAIL_PASSWORD}
      - mail__options__service=${MAIL_SERVICE}
    expose:
      - 8632
    volumes:
      - ghost_data:/var/lib/ghost/content
    deploy:
      placement:
        constraints:
          - node.role == worker
volumes:
  ghost_data: {}
