services:
  postgres:
    image: postgres:17-alpine3.21
    container_name: postgres
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=postgres
      - PG_DATA=/var/lib/postgresql/data
    volumes:
      - postgres_data:/var/lib/postgresql/data
    deploy:
      placement:
        constraints:
          - node.role == worker
    replicas: 1
volumes:
  postgres_data: {}
